# -*- coding: utf-8 -*-
"""VRSU- lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F57ylICFQV-KRj8ac-6K-KDeNdAglQ6H
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Find image automatically
image_path = None
for file in os.listdir("/content"):
    if "flower" in file.lower():
        image_path = "/content/" + file
        break

if image_path is None:
    raise FileNotFoundError("No flower image found. Please upload flower.jpg")

# Load image
img = cv2.imread(image_path)

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Binary Threshold
T = 127
_, binary = cv2.threshold(gray, T, 255, cv2.THRESH_BINARY)

# Otsu Threshold
otsu_T, otsu = cv2.threshold(
    gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

# Display
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.title("Grayscale Image")
plt.imshow(gray, cmap='gray')
plt.axis("off")

plt.subplot(1,3,2)
plt.title(f"Binary Threshold (T={T})")
plt.imshow(binary, cmap='gray')
plt.axis("off")

plt.subplot(1,3,3)
plt.title(f"Otsu Threshold (T={int(otsu_T)})")
plt.imshow(otsu, cmap='gray')
plt.axis("off")

plt.tight_layout()
plt.show()