# -*- coding: utf-8 -*-
"""VRSU-img enhancement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPWnGIZ4S9-Mq31VL6vuZMdAwgsA3TFs
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Image paths
path_avg = "/content/sample_data/avg1.jpg"
path_gauss = "/content/sample_data/gauss1.webp"
path_median = "/content/sample_data/median1.webp"

# Load images
img_avg = cv2.imread(path_avg, cv2.IMREAD_COLOR)
img_gauss = cv2.imread(path_gauss, cv2.IMREAD_COLOR)
img_median = cv2.imread(path_median, cv2.IMREAD_COLOR)

# Validate image loading
if img_avg is None:
    raise FileNotFoundError(f"Cannot load {path_avg}")
if img_gauss is None:
    raise FileNotFoundError(f"Cannot load {path_gauss} (Check WebP support & path)")
if img_median is None:
    raise FileNotFoundError(f"Cannot load {path_median} (Check WebP support & path)")

# Convert BGR to RGB
img_avg = cv2.cvtColor(img_avg, cv2.COLOR_BGR2RGB)
img_gauss = cv2.cvtColor(img_gauss, cv2.COLOR_BGR2RGB)
img_median = cv2.cvtColor(img_median, cv2.COLOR_BGR2RGB)

# Apply smoothing
avg_smooth = cv2.blur(img_avg, (5, 5))
gauss_smooth = cv2.GaussianBlur(img_gauss, (5, 5), sigmaX=1.5)
median_smooth = cv2.medianBlur(img_median, 5)

# Display results
plt.figure(figsize=(12, 10))

plt.subplot(3, 2, 1)
plt.title("Original - Average Image (.jpg)")
plt.imshow(img_avg)
plt.axis("off")

plt.subplot(3, 2, 2)
plt.title("Average Smoothed")
plt.imshow(avg_smooth)
plt.axis("off")

plt.subplot(3, 2, 3)
plt.title("Original - Gaussian Image (.webp)")
plt.imshow(img_gauss)
plt.axis("off")

plt.subplot(3, 2, 4)
plt.title("Gaussian Smoothed")
plt.imshow(gauss_smooth)
plt.axis("off")

plt.subplot(3, 2, 5)
plt.title("Original - Median Image (.webp)")
plt.imshow(img_median)
plt.axis("off")

plt.subplot(3, 2, 6)
plt.title("Median Smoothed")
plt.imshow(median_smooth)
plt.axis("off")

plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load image
img = cv2.imread("/content/sample_data/flower.jpg")

# Check if image is loaded
if img is None:
    raise FileNotFoundError("flower.jpg not found in /content/sample_data")

# Convert BGR to RGB
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Define sharpening kernel
sharpen_kernel = np.array([[0, -1, 0],
                           [-1, 5, -1],
                           [0, -1, 0]])

# Apply sharpening
sharpened = cv2.filter2D(img, -1, sharpen_kernel)

# Display results
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.title("Original Image")
plt.imshow(img)
plt.axis("off")

plt.subplot(1, 2, 2)
plt.title("Sharpened Image")
plt.imshow(sharpened)
plt.axis("off")

plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load image
img = cv2.imread("/content/sample_data/flower.jpg")

# Check if image loaded
if img is None:
    raise FileNotFoundError("flower.jpg not found in /content/sample_data")

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# -----------------------------
# Sobel Edge Detection
# -----------------------------
sobel_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
sobel_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)

sobel_magnitude = cv2.magnitude(sobel_x, sobel_y)
sobel_magnitude = np.uint8(sobel_magnitude)

# -----------------------------
# Canny Edge Detection
# -----------------------------
canny_edges = cv2.Canny(gray, threshold1=100, threshold2=200)

# Convert original image to RGB for display
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# -----------------------------
# Display Results
# -----------------------------
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.title("Original Image")
plt.imshow(img_rgb)
plt.axis("off")

plt.subplot(1, 3, 2)
plt.title("Sobel Edge Detection")
plt.imshow(sobel_magnitude, cmap='gray')
plt.axis("off")

plt.subplot(1, 3, 3)
plt.title("Canny Edge Detection")
plt.imshow(canny_edges, cmap='gray')
plt.axis("off")

plt.tight_layout()
plt.show()